name: school_app_mvp
description:  A student management software
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  http: ^1.2.2
  shared_preferences: ^2.1.0
  flutter_svg: ^1.1.0
  syncfusion_flutter_pdfviewer: ^31.1.21
  google_fonts: ^6.2.1
  dio: ^5.9.0
  riverpod: ^3.0.3
  flutter_riverpod: ^3.0.3


flutter_native_splash:
  color: "#F7F7FB"         # Background color (your scaffoldBg maybe)
  image: assets/images/logo.png   # Path to your logo
  android: true
  ios: true
  web: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash:
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/logo.png
  adaptive_icon_foreground: assets/images/logo.png
  adaptive_icon_background: "#FFFFFF"
  web:
    generate: true
    image_path: assets/images/logo.png
    background_color: "#F7F7FB"
    theme_color: "#1976D2"
  windows:
    generate: true
    image_path: assets/images/logo.png
  macos:
    generate: true
    image_path: assets/images/logo.png

